plugins { id 'com.android.application'; id 'kotlin-android' }

android {
    namespace 'com.feelcool.tv'
    compileSdk 33
    defaultConfig { 
        applicationId "com.feelcool.tv"
        minSdk 23 // 兼容大部分老旧电视
        targetSdk 33 
        versionCode 1; versionName "1.0" 
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    // 引入 Google 官方的顶级播放器 ExoPlayer (Media3)
    implementation 'androidx.media3:media3-exoplayer:1.1.1'
    implementation 'androidx.media3:media3-ui:1.1.1'
    implementation 'androidx.media3:media3-exoplayer-hls:1.1.1' // 专门用来解析 m3u8 直播流
}
